INSERT INTO [Course] values (1, 'Essentials of Psychology', 'Mathematics');
 INSERT INTO [Course] values (2, 'Fundamentals of Chemistry', 'Sociology');
 INSERT INTO [Course] values (3, 'Advanced Biology', 'Mathematics');
 INSERT INTO [Course] values (4, 'Intro to Computer Science', 'Physics');
 INSERT INTO [Course] values (5, 'Advanced Computer Science', 'Physics');
 INSERT INTO [Course] values (6, 'Essentials of Psychology', 'Engineering');
 INSERT INTO [Course] values (7, 'Applied Computer Science', 'Computer Science');
 INSERT INTO [Course] values (8, 'Principles of Chemistry', 'Mathematics');
 INSERT INTO [Course] values (9, 'Fundamentals of Engineering', 'History');
 INSERT INTO [Course] values (10, 'Advanced Sociology', 'History');
 INSERT INTO [Course] values (11, 'Advanced Engineering', 'Physics');
 INSERT INTO [Course] values (12, 'Essentials of Psychology', 'Physics');
 INSERT INTO [Course] values (13, 'Essentials of Psychology', 'History');
 INSERT INTO [Course] values (14, 'Essentials of Chemistry', 'History');
 INSERT INTO [Course] values (15, 'Advanced Mathematics', 'Biology');
 INSERT INTO [Course] values (16, 'Fundamentals of Computer Science', 'Chemistry');
 INSERT INTO [Course] values (17, 'Fundamentals of English', 'English');
 INSERT INTO [Course] values (18, 'Intro to History', 'Engineering');
 INSERT INTO [Course] values (19, 'Advanced Psychology', 'English');
 INSERT INTO [Course] values (20, 'Advanced Physics', 'Engineering');
 INSERT INTO [Course] values (21, 'Advanced Chemistry', 'English');
 INSERT INTO [Course] values (22, 'Applied Biology', 'Mathematics');
 INSERT INTO [Course] values (23, 'Essentials of Sociology', 'Physics');
 INSERT INTO [Course] values (24, 'Principles of Computer Science', 'Mathematics');
 INSERT INTO [Course] values (25, 'Intro to Psychology', 'History');
 INSERT INTO [Course] values (26, 'Principles of Engineering', 'Engineering');
 INSERT INTO [Course] values (27, 'Advanced Chemistry', 'Chemistry');
 INSERT INTO [Course] values (28, 'Fundamentals of Psychology', 'Sociology');
 INSERT INTO [Course] values (29, 'Essentials of Chemistry', 'Sociology');
 INSERT INTO [Course] values (30, 'Applied Psychology', 'Psychology');
 INSERT INTO [Course] values (31, 'Applied Psychology', 'Computer Science');
 INSERT INTO [Course] values (32, 'Principles of Engineering', 'Psychology');
 INSERT INTO [Course] values (33, 'Intro to History', 'Psychology');
 INSERT INTO [Course] values (34, 'Intro to English', 'Mathematics');
 INSERT INTO [Course] values (35, 'Advanced Biology', 'Engineering');
 INSERT INTO [Course] values (36, 'Intro to Engineering', 'History');
 INSERT INTO [Course] values (37, 'Advanced Engineering', 'Biology');
 INSERT INTO [Course] values (38, 'Principles of Mathematics', 'Chemistry');
 INSERT INTO [Course] values (39, 'Advanced Psychology', 'Physics');
 INSERT INTO [Course] values (40, 'Applied English', 'History');
 INSERT INTO [Course] values (41, 'Applied History', 'Mathematics');
 INSERT INTO [Course] values (42, 'Fundamentals of Computer Science', 'Computer Science');
 INSERT INTO [Course] values (43, 'Advanced Chemistry', 'Chemistry');
 INSERT INTO [Course] values (44, 'Intro to Chemistry', 'English');
 INSERT INTO [Course] values (45, 'Advanced Physics', 'Engineering');
 INSERT INTO [Course] values (46, 'Essentials of Computer Science', 'Mathematics');
 INSERT INTO [Course] values (47, 'Fundamentals of English', 'Engineering');
 INSERT INTO [Course] values (48, 'Advanced English', 'Engineering');
 INSERT INTO [Course] values (49, 'Fundamentals of Psychology', 'Biology');
 INSERT INTO [Course] values (50, 'Essentials of Psychology', 'Physics');
 INSERT INTO [Course] values (51, 'Intro to English', 'Biology');
 INSERT INTO [Course] values (52, 'Principles of Engineering', 'Computer Science');
 INSERT INTO [Course] values (53, 'Principles of Chemistry', 'Sociology');
 INSERT INTO [Course] values (54, 'Intro to Engineering', 'History');
 INSERT INTO [Course] values (55, 'Advanced Biology', 'Chemistry');
 INSERT INTO [Course] values (56, 'Fundamentals of Computer Science', 'Biology');
 INSERT INTO [Course] values (57, 'Essentials of Biology', 'Mathematics');
 INSERT INTO [Course] values (58, 'Applied Chemistry', 'English');
 INSERT INTO [Course] values (59, 'Principles of Chemistry', 'History');
 INSERT INTO [Course] values (60, 'Applied Chemistry', 'Physics');
 INSERT INTO [Course] values (61, 'Applied Engineering', 'History');
 INSERT INTO [Course] values (62, 'Advanced English', 'Computer Science');
 INSERT INTO [Course] values (63, 'Fundamentals of History', 'Engineering');
 INSERT INTO [Course] values (64, 'Applied Engineering', 'Sociology');
 INSERT INTO [Course] values (65, 'Fundamentals of Sociology', 'Chemistry');
 INSERT INTO [Course] values (66, 'Applied English', 'Sociology');
 INSERT INTO [Course] values (67, 'Applied History', 'Psychology');
 INSERT INTO [Course] values (68, 'Applied Engineering', 'Psychology');
 INSERT INTO [Course] values (69, 'Fundamentals of Engineering', 'English');
 INSERT INTO [Course] values (70, 'Essentials of Biology', 'Engineering');
 INSERT INTO [Course] values (71, 'Essentials of English', 'Chemistry');
 INSERT INTO [Course] values (72, 'Advanced Biology', 'Computer Science');
 INSERT INTO [Course] values (73, 'Principles of Chemistry', 'English');
 INSERT INTO [Course] values (74, 'Intro to Engineering', 'Mathematics');
 INSERT INTO [Course] values (75, 'Essentials of Biology', 'English');
 INSERT INTO [Course] values (76, 'Essentials of Computer Science', 'Computer Science');
 INSERT INTO [Course] values (77, 'Intro to English', 'Biology');
 INSERT INTO [Course] values (78, 'Fundamentals of Biology', 'Mathematics');
 INSERT INTO [Course] values (79, 'Fundamentals of Mathematics', 'English');
 INSERT INTO [Course] values (80, 'Principles of Chemistry', 'Biology');
 INSERT INTO [Course] values (81, 'Applied Engineering', 'Mathematics');
 INSERT INTO [Course] values (82, 'Applied Engineering', 'Mathematics');
 INSERT INTO [Course] values (83, 'Advanced Computer Science', 'English');
 INSERT INTO [Course] values (84, 'Fundamentals of History', 'Computer Science');
 INSERT INTO [Course] values (85, 'Fundamentals of Sociology', 'Sociology');
 INSERT INTO [Course] values (86, 'Intro to English', 'Chemistry');
 INSERT INTO [Course] values (87, 'Essentials of Psychology', 'History');
 INSERT INTO [Course] values (88, 'Essentials of Mathematics', 'Mathematics');
 INSERT INTO [Course] values (89, 'Applied Biology', 'English');
 INSERT INTO [Course] values (90, 'Applied Psychology', 'Chemistry');
 INSERT INTO [Course] values (91, 'Advanced Mathematics', 'History');
 INSERT INTO [Course] values (92, 'Essentials of Physics', 'Psychology');
 INSERT INTO [Course] values (93, 'Fundamentals of Engineering', 'History');
 INSERT INTO [Course] values (94, 'Principles of English', 'Sociology');
 INSERT INTO [Course] values (95, 'Advanced Computer Science', 'Computer Science');
 INSERT INTO [Course] values (96, 'Applied Chemistry', 'History');
 INSERT INTO [Course] values (97, 'Advanced Psychology', 'Computer Science');
 INSERT INTO [Course] values (98, 'Applied Mathematics', 'Physics');
 INSERT INTO [Course] values (99, 'Principles of English', 'Sociology');
 INSERT INTO [Course] values (100, 'Principles of History', 'Sociology');
 INSERT INTO [Course] values (101, 'Principles of Biology', 'Physics');
 INSERT INTO [Course] values (102, 'Essentials of Chemistry', 'Psychology');
 INSERT INTO [Course] values (103, 'Principles of History', 'Computer Science');
 INSERT INTO [Course] values (104, 'Essentials of Mathematics', 'Physics');
 INSERT INTO [Course] values (105, 'Intro to Mathematics', 'Psychology');
 INSERT INTO [Course] values (106, 'Fundamentals of Physics', 'English');
 INSERT INTO [Course] values (107, 'Principles of History', 'English');
 INSERT INTO [Course] values (108, 'Advanced Biology', 'English');
 INSERT INTO [Course] values (109, 'Fundamentals of English', 'Sociology');
 INSERT INTO [Course] values (110, 'Intro to Chemistry', 'Computer Science');
 INSERT INTO [Course] values (111, 'Principles of Computer Science', 'Computer Science');
 INSERT INTO [Course] values (112, 'Intro to Mathematics', 'History');
 INSERT INTO [Course] values (113, 'Advanced English', 'Psychology');
 INSERT INTO [Course] values (114, 'Applied Physics', 'Psychology');
 INSERT INTO [Course] values (115, 'Intro to Biology', 'Psychology');
 INSERT INTO [Course] values (116, 'Advanced Physics', 'Biology');
 INSERT INTO [Course] values (117, 'Principles of Engineering', 'Physics');
 INSERT INTO [Course] values (118, 'Fundamentals of Engineering', 'English');
 INSERT INTO [Course] values (119, 'Fundamentals of History', 'Computer Science');
 INSERT INTO [Course] values (120, 'Principles of Sociology', 'History');
 INSERT INTO [Course] values (121, 'Advanced Computer Science', 'Biology');
 INSERT INTO [Course] values (122, 'Principles of Sociology', 'Computer Science');
 INSERT INTO [Course] values (123, 'Principles of Psychology', 'Chemistry');
 INSERT INTO [Course] values (124, 'Essentials of Chemistry', 'Sociology');
 INSERT INTO [Course] values (125, 'Essentials of Psychology', 'English');
 INSERT INTO [Course] values (126, 'Applied English', 'History');
 INSERT INTO [Course] values (127, 'Applied Psychology', 'Chemistry');
 INSERT INTO [Course] values (128, 'Principles of History', 'Mathematics');
 INSERT INTO [Course] values (129, 'Essentials of History', 'Sociology');
 INSERT INTO [Course] values (130, 'Applied English', 'Psychology');
 INSERT INTO [Course] values (131, 'Applied History', 'Mathematics');
 INSERT INTO [Course] values (132, 'Essentials of English', 'History');
 INSERT INTO [Course] values (133, 'Intro to Chemistry', 'Psychology');
 INSERT INTO [Course] values (134, 'Advanced Computer Science', 'Chemistry');
 INSERT INTO [Course] values (135, 'Intro to History', 'Engineering');
 INSERT INTO [Course] values (136, 'Principles of Physics', 'English');
 INSERT INTO [Course] values (137, 'Principles of English', 'English');
 INSERT INTO [Course] values (138, 'Intro to Engineering', 'Computer Science');
 INSERT INTO [Course] values (139, 'Advanced Psychology', 'Psychology');
 INSERT INTO [Course] values (140, 'Essentials of English', 'Mathematics');
 INSERT INTO [Course] values (141, 'Fundamentals of Physics', 'Psychology');
 INSERT INTO [Course] values (142, 'Advanced Computer Science', 'Biology');
 INSERT INTO [Course] values (143, 'Intro to Biology', 'Sociology');
 INSERT INTO [Course] values (144, 'Essentials of Mathematics', 'Physics');
 INSERT INTO [Course] values (145, 'Principles of Chemistry', 'Psychology');
 INSERT INTO [Course] values (146, 'Advanced Physics', 'Computer Science');
 INSERT INTO [Course] values (147, 'Principles of Mathematics', 'Engineering');
 INSERT INTO [Course] values (148, 'Intro to Chemistry', 'Biology');
 INSERT INTO [Course] values (149, 'Advanced Chemistry', 'History');
 INSERT INTO [Course] values (150, 'Applied Engineering', 'History');
 INSERT INTO [Course] values (151, 'Principles of Biology', 'Sociology');
 INSERT INTO [Course] values (152, 'Fundamentals of Biology', 'Sociology');
 INSERT INTO [Course] values (153, 'Fundamentals of Biology', 'Computer Science');
 INSERT INTO [Course] values (154, 'Essentials of History', 'Mathematics');
 INSERT INTO [Course] values (155, 'Advanced Engineering', 'Mathematics');
 INSERT INTO [Course] values (156, 'Principles of Physics', 'Chemistry');
 INSERT INTO [Course] values (157, 'Intro to Chemistry', 'Biology');
 INSERT INTO [Course] values (158, 'Intro to History', 'Engineering');
 INSERT INTO [Course] values (159, 'Advanced Mathematics', 'Physics');
 INSERT INTO [Course] values (160, 'Intro to Computer Science', 'Sociology');
 INSERT INTO [Course] values (161, 'Essentials of English', 'Chemistry');
 INSERT INTO [Course] values (162, 'Applied History', 'Psychology');
 INSERT INTO [Course] values (163, 'Intro to Engineering', 'Chemistry');
 INSERT INTO [Course] values (164, 'Intro to Mathematics', 'History');
 INSERT INTO [Course] values (165, 'Advanced Computer Science', 'Engineering');
 INSERT INTO [Course] values (166, 'Applied Engineering', 'Biology');
 INSERT INTO [Course] values (167, 'Principles of Biology', 'Physics');
 INSERT INTO [Course] values (168, 'Essentials of Biology', 'English');
 INSERT INTO [Course] values (169, 'Intro to Sociology', 'Mathematics');
 INSERT INTO [Course] values (170, 'Essentials of Physics', 'Mathematics');
 INSERT INTO [Course] values (171, 'Advanced Engineering', 'Chemistry');
 INSERT INTO [Course] values (172, 'Applied Biology', 'Biology');
 INSERT INTO [Course] values (173, 'Intro to Engineering', 'English');
 INSERT INTO [Course] values (174, 'Principles of Mathematics', 'Psychology');
 INSERT INTO [Course] values (175, 'Fundamentals of Biology', 'Mathematics');
 INSERT INTO [Course] values (176, 'Applied Physics', 'Psychology');
 INSERT INTO [Course] values (177, 'Applied History', 'Physics');
 INSERT INTO [Course] values (178, 'Principles of Chemistry', 'History');
 INSERT INTO [Course] values (179, 'Essentials of Psychology', 'History');
 INSERT INTO [Course] values (180, 'Essentials of Computer Science', 'Computer Science');
 INSERT INTO [Course] values (181, 'Principles of Biology', 'Engineering');
 INSERT INTO [Course] values (182, 'Principles of Mathematics', 'Biology');
 INSERT INTO [Course] values (183, 'Applied Engineering', 'Sociology');
 INSERT INTO [Course] values (184, 'Applied History', 'Physics');
 INSERT INTO [Course] values (185, 'Intro to History', 'Mathematics');
 INSERT INTO [Course] values (186, 'Advanced Engineering', 'English');
 INSERT INTO [Course] values (187, 'Essentials of Engineering', 'English');
 INSERT INTO [Course] values (188, 'Principles of Engineering', 'Biology');
 INSERT INTO [Course] values (189, 'Intro to Computer Science', 'Chemistry');
 INSERT INTO [Course] values (190, 'Fundamentals of Psychology', 'Biology');
 INSERT INTO [Course] values (191, 'Intro to Physics', 'Biology');
 INSERT INTO [Course] values (192, 'Intro to Computer Science', 'Engineering');
 INSERT INTO [Course] values (193, 'Essentials of History', 'History');
 INSERT INTO [Course] values (194, 'Applied English', 'English');
 INSERT INTO [Course] values (195, 'Advanced Mathematics', 'Mathematics');
 INSERT INTO [Course] values (196, 'Intro to Physics', 'Physics');
 INSERT INTO [Course] values (197, 'Principles of Physics', 'Sociology');
 INSERT INTO [Course] values (198, 'Fundamentals of History', 'Computer Science');
 INSERT INTO [Course] values (199, 'Fundamentals of History', 'Mathematics');
 INSERT INTO [Course] values (200, 'Applied History', 'Mathematics');
 INSERT INTO [Course] values (201, 'Principles of Chemistry', 'Mathematics');
 INSERT INTO [Course] values (202, 'Fundamentals of Sociology', 'Engineering');
 INSERT INTO [Course] values (203, 'Applied Physics', 'Biology');
 INSERT INTO [Course] values (204, 'Intro to Biology', 'Engineering');
 INSERT INTO [Course] values (205, 'Advanced Biology', 'Physics');
 INSERT INTO [Course] values (206, 'Essentials of Physics', 'English');
 INSERT INTO [Course] values (207, 'Intro to Engineering', 'Biology');
 INSERT INTO [Course] values (208, 'Applied Computer Science', 'English');
 INSERT INTO [Course] values (209, 'Essentials of Biology', 'Computer Science');
 INSERT INTO [Course] values (210, 'Applied History', 'Sociology');
 INSERT INTO [Course] values (211, 'Essentials of Computer Science', 'Chemistry');
 INSERT INTO [Course] values (212, 'Applied Computer Science', 'Biology');
 INSERT INTO [Course] values (213, 'Fundamentals of Chemistry', 'Engineering');
 INSERT INTO [Course] values (214, 'Essentials of English', 'English');
 INSERT INTO [Course] values (215, 'Applied Biology', 'History');
 INSERT INTO [Course] values (216, 'Essentials of Computer Science', 'Psychology');
 INSERT INTO [Course] values (217, 'Intro to Computer Science', 'Computer Science');
 INSERT INTO [Course] values (218, 'Principles of Engineering', 'Chemistry');
 INSERT INTO [Course] values (219, 'Intro to Sociology', 'Computer Science');
 INSERT INTO [Course] values (220, 'Advanced Computer Science', 'Computer Science');
 INSERT INTO [Course] values (221, 'Advanced Mathematics', 'History');
 INSERT INTO [Course] values (222, 'Intro to Psychology', 'Biology');
 INSERT INTO [Course] values (223, 'Applied Chemistry', 'Physics');
 INSERT INTO [Course] values (224, 'Essentials of Computer Science', 'Mathematics');
 INSERT INTO [Course] values (225, 'Applied Mathematics', 'Chemistry');
 INSERT INTO [Course] values (226, 'Applied Engineering', 'Chemistry');
 INSERT INTO [Course] values (227, 'Applied English', 'Engineering');
 INSERT INTO [Course] values (228, 'Essentials of Computer Science', 'Psychology');
 INSERT INTO [Course] values (229, 'Applied English', 'Psychology');
 INSERT INTO [Course] values (230, 'Intro to Biology', 'English');
 INSERT INTO [Course] values (231, 'Essentials of Engineering', 'History');
 INSERT INTO [Course] values (232, 'Intro to Mathematics', 'English');
 INSERT INTO [Course] values (233, 'Principles of Physics', 'English');
 INSERT INTO [Course] values (234, 'Advanced Mathematics', 'Computer Science');
 INSERT INTO [Course] values (235, 'Fundamentals of Mathematics', 'Mathematics');
 INSERT INTO [Course] values (236, 'Applied Sociology', 'Chemistry');
 INSERT INTO [Course] values (237, 'Applied Physics', 'Chemistry');
 INSERT INTO [Course] values (238, 'Fundamentals of Physics', 'Computer Science');
 INSERT INTO [Course] values (239, 'Principles of Chemistry', 'Mathematics');
 INSERT INTO [Course] values (240, 'Essentials of History', 'History');
 INSERT INTO [Course] values (241, 'Intro to Psychology', 'Physics');
 INSERT INTO [Course] values (242, 'Fundamentals of Sociology', 'Chemistry');
 INSERT INTO [Course] values (243, 'Applied History', 'Engineering');
 INSERT INTO [Course] values (244, 'Intro to Chemistry', 'Psychology');
 INSERT INTO [Course] values (245, 'Applied English', 'Engineering');
 INSERT INTO [Course] values (246, 'Principles of Physics', 'Mathematics');
 INSERT INTO [Course] values (247, 'Applied Physics', 'Physics');
 INSERT INTO [Course] values (248, 'Intro to Mathematics', 'Psychology');
 INSERT INTO [Course] values (249, 'Applied Computer Science', 'Biology');
 INSERT INTO [Course] values (250, 'Advanced Engineering', 'Computer Science');
 INSERT INTO [Course] values (251, 'Fundamentals of English', 'English');
 INSERT INTO [Course] values (252, 'Intro to Physics', 'History');
 INSERT INTO [Course] values (253, 'Fundamentals of Chemistry', 'Psychology');
 INSERT INTO [Course] values (254, 'Intro to History', 'Computer Science');
 INSERT INTO [Course] values (255, 'Fundamentals of Biology', 'English');
 INSERT INTO [Course] values (256, 'Applied Sociology', 'Biology');
 INSERT INTO [Course] values (257, 'Essentials of Sociology', 'Computer Science');
 INSERT INTO [Course] values (258, 'Advanced Biology', 'Engineering');
 INSERT INTO [Course] values (259, 'Essentials of Physics', 'Biology');
 INSERT INTO [Course] values (260, 'Intro to Computer Science', 'Biology');
 INSERT INTO [Course] values (261, 'Principles of Engineering', 'Sociology');
 INSERT INTO [Course] values (262, 'Fundamentals of Physics', 'Chemistry');
 INSERT INTO [Course] values (263, 'Essentials of Computer Science', 'Psychology');
 INSERT INTO [Course] values (264, 'Advanced Physics', 'Sociology');
 INSERT INTO [Course] values (265, 'Fundamentals of Mathematics', 'Computer Science');
 INSERT INTO [Course] values (266, 'Intro to Biology', 'Physics');
 INSERT INTO [Course] values (267, 'Applied Mathematics', 'Chemistry');
 INSERT INTO [Course] values (268, 'Advanced Physics', 'Computer Science');
 INSERT INTO [Course] values (269, 'Fundamentals of English', 'Mathematics');
 INSERT INTO [Course] values (270, 'Fundamentals of History', 'History');
 INSERT INTO [Course] values (271, 'Applied History', 'Computer Science');
 INSERT INTO [Course] values (272, 'Essentials of Engineering', 'Computer Science');
 INSERT INTO [Course] values (273, 'Fundamentals of Physics', 'Psychology');
 INSERT INTO [Course] values (274, 'Essentials of English', 'Mathematics');
 INSERT INTO [Course] values (275, 'Advanced Biology', 'Sociology');
 INSERT INTO [Course] values (276, 'Intro to Sociology', 'Computer Science');
 INSERT INTO [Course] values (277, 'Applied History', 'Engineering');
 INSERT INTO [Course] values (278, 'Intro to History', 'Computer Science');
 INSERT INTO [Course] values (279, 'Fundamentals of Physics', 'Chemistry');
 INSERT INTO [Course] values (280, 'Advanced Chemistry', 'Computer Science');
 INSERT INTO [Course] values (281, 'Advanced English', 'Engineering');
 INSERT INTO [Course] values (282, 'Intro to Mathematics', 'Mathematics');
 INSERT INTO [Course] values (283, 'Essentials of Mathematics', 'Computer Science');
 INSERT INTO [Course] values (284, 'Essentials of English', 'Chemistry');
 INSERT INTO [Course] values (285, 'Essentials of Psychology', 'Biology');
 INSERT INTO [Course] values (286, 'Essentials of Engineering', 'Computer Science');
 INSERT INTO [Course] values (287, 'Principles of Biology', 'Sociology');
 INSERT INTO [Course] values (288, 'Intro to Sociology', 'Psychology');
 INSERT INTO [Course] values (289, 'Principles of Mathematics', 'English');
 INSERT INTO [Course] values (290, 'Principles of English', 'Computer Science');
 INSERT INTO [Course] values (291, 'Essentials of Mathematics', 'Engineering');
 INSERT INTO [Course] values (292, 'Advanced Engineering', 'Computer Science');
 INSERT INTO [Course] values (293, 'Essentials of Mathematics', 'Chemistry');
 INSERT INTO [Course] values (294, 'Intro to Psychology', 'Chemistry');
 INSERT INTO [Course] values (295, 'Fundamentals of Computer Science', 'Biology');
 INSERT INTO [Course] values (296, 'Principles of Engineering', 'Chemistry');
 INSERT INTO [Course] values (297, 'Intro to Chemistry', 'Engineering');
 INSERT INTO [Course] values (298, 'Intro to Chemistry', 'Physics');
 INSERT INTO [Course] values (299, 'Advanced Biology', 'Sociology');
 INSERT INTO [Course] values (300, 'Essentials of Biology', 'Biology');
 INSERT INTO [Course] values (301, 'Applied Mathematics', 'Physics');
 INSERT INTO [Course] values (302, 'Fundamentals of Chemistry', 'Biology');
 INSERT INTO [Course] values (303, 'Applied Mathematics', 'Chemistry');
 INSERT INTO [Course] values (304, 'Applied Mathematics', 'Sociology');
 INSERT INTO [Course] values (305, 'Advanced Physics', 'Mathematics');
 INSERT INTO [Course] values (306, 'Fundamentals of Psychology', 'Chemistry');
 INSERT INTO [Course] values (307, 'Intro to Sociology', 'Physics');
 INSERT INTO [Course] values (308, 'Principles of Engineering', 'History');
 INSERT INTO [Course] values (309, 'Fundamentals of Chemistry', 'Physics');
 INSERT INTO [Course] values (310, 'Essentials of Engineering', 'Sociology');
 INSERT INTO [Course] values (311, 'Advanced History', 'History');
 INSERT INTO [Course] values (312, 'Fundamentals of Computer Science', 'Sociology');
 INSERT INTO [Course] values (313, 'Fundamentals of Chemistry', 'Mathematics');
 INSERT INTO [Course] values (314, 'Fundamentals of Computer Science', 'Sociology');
 INSERT INTO [Course] values (315, 'Essentials of Biology', 'Biology');
 INSERT INTO [Course] values (316, 'Intro to English', 'Computer Science');
 INSERT INTO [Course] values (317, 'Intro to Physics', 'Biology');
 INSERT INTO [Course] values (318, 'Intro to Engineering', 'Computer Science');
 INSERT INTO [Course] values (319, 'Advanced Psychology', 'Sociology');
 INSERT INTO [Course] values (320, 'Applied Mathematics', 'Physics');
 INSERT INTO [Course] values (321, 'Advanced Physics', 'Mathematics');
 INSERT INTO [Course] values (322, 'Applied Sociology', 'Sociology');
 INSERT INTO [Course] values (323, 'Essentials of Computer Science', 'Sociology');
 INSERT INTO [Course] values (324, 'Essentials of Physics', 'Mathematics');
 INSERT INTO [Course] values (325, 'Intro to Biology', 'History');
 INSERT INTO [Course] values (326, 'Fundamentals of History', 'Physics');
 INSERT INTO [Course] values (327, 'Principles of Engineering', 'Chemistry');
 INSERT INTO [Course] values (328, 'Principles of English', 'Biology');
 INSERT INTO [Course] values (329, 'Fundamentals of Physics', 'Biology');
 INSERT INTO [Course] values (330, 'Intro to Chemistry', 'Biology');
 INSERT INTO [Course] values (331, 'Applied Chemistry', 'Psychology');
 INSERT INTO [Course] values (332, 'Applied History', 'Mathematics');
 INSERT INTO [Course] values (333, 'Applied Mathematics', 'Chemistry');
 INSERT INTO [Course] values (334, 'Principles of Psychology', 'English');
 INSERT INTO [Course] values (335, 'Applied Engineering', 'Engineering');
 INSERT INTO [Course] values (336, 'Fundamentals of Chemistry', 'Computer Science');
 INSERT INTO [Course] values (337, 'Intro to Mathematics', 'Biology');
 INSERT INTO [Course] values (338, 'Principles of Sociology', 'Psychology');
 INSERT INTO [Course] values (339, 'Intro to History', 'Chemistry');
 INSERT INTO [Course] values (340, 'Principles of Psychology', 'Chemistry');
 INSERT INTO [Course] values (341, 'Principles of Engineering', 'Mathematics');
 INSERT INTO [Course] values (342, 'Intro to Sociology', 'Computer Science');
 INSERT INTO [Course] values (343, 'Fundamentals of Mathematics', 'Engineering');
 INSERT INTO [Course] values (344, 'Essentials of English', 'Physics');
 INSERT INTO [Course] values (345, 'Fundamentals of Psychology', 'Computer Science');
 INSERT INTO [Course] values (346, 'Advanced Chemistry', 'Sociology');
 INSERT INTO [Course] values (347, 'Applied History', 'Biology');
 INSERT INTO [Course] values (348, 'Essentials of Psychology', 'History');
 INSERT INTO [Course] values (349, 'Principles of Chemistry', 'Chemistry');
 INSERT INTO [Course] values (350, 'Essentials of Computer Science', 'Mathematics');
 INSERT INTO [Course] values (351, 'Principles of Computer Science', 'Physics');
 INSERT INTO [Course] values (352, 'Principles of Biology', 'History');
 INSERT INTO [Course] values (353, 'Advanced Biology', 'Chemistry');
 INSERT INTO [Course] values (354, 'Intro to Computer Science', 'English');
 INSERT INTO [Course] values (355, 'Intro to Chemistry', 'Sociology');
 INSERT INTO [Course] values (356, 'Advanced Sociology', 'Psychology');
 INSERT INTO [Course] values (357, 'Intro to Biology', 'Physics');
 INSERT INTO [Course] values (358, 'Essentials of History', 'English');
 INSERT INTO [Course] values (359, 'Principles of Chemistry', 'Chemistry');
 INSERT INTO [Course] values (360, 'Principles of History', 'Sociology');
 INSERT INTO [Course] values (361, 'Essentials of Chemistry', 'Physics');
 INSERT INTO [Course] values (362, 'Principles of Mathematics', 'Computer Science');
 INSERT INTO [Course] values (363, 'Advanced Computer Science', 'Sociology');
 INSERT INTO [Course] values (364, 'Applied Chemistry', 'Physics');
 INSERT INTO [Course] values (365, 'Essentials of Physics', 'Biology');
 INSERT INTO [Course] values (366, 'Essentials of Mathematics', 'Biology');
 INSERT INTO [Course] values (367, 'Intro to Psychology', 'Chemistry');
 INSERT INTO [Course] values (368, 'Principles of Engineering', 'Chemistry');
 INSERT INTO [Course] values (369, 'Essentials of Engineering', 'Physics');
 INSERT INTO [Course] values (370, 'Principles of History', 'Physics');
 INSERT INTO [Course] values (371, 'Essentials of History', 'Computer Science');
 INSERT INTO [Course] values (372, 'Fundamentals of Biology', 'Sociology');
 INSERT INTO [Course] values (373, 'Fundamentals of Chemistry', 'Computer Science');
 INSERT INTO [Course] values (374, 'Applied Chemistry', 'Computer Science');
 INSERT INTO [Course] values (375, 'Principles of Physics', 'Mathematics');
 INSERT INTO [Course] values (376, 'Principles of Engineering', 'Engineering');
 INSERT INTO [Course] values (377, 'Essentials of Psychology', 'Sociology');
 INSERT INTO [Course] values (378, 'Essentials of English', 'Biology');
 INSERT INTO [Course] values (379, 'Essentials of Mathematics', 'Psychology');
 INSERT INTO [Course] values (380, 'Intro to Computer Science', 'Sociology');
 INSERT INTO [Course] values (381, 'Applied Engineering', 'Sociology');
 INSERT INTO [Course] values (382, 'Principles of Chemistry', 'Psychology');
 INSERT INTO [Course] values (383, 'Advanced English', 'Computer Science');
 INSERT INTO [Course] values (384, 'Essentials of History', 'Sociology');
 INSERT INTO [Course] values (385, 'Principles of Physics', 'Physics');
 INSERT INTO [Course] values (386, 'Advanced Chemistry', 'Engineering');
 INSERT INTO [Course] values (387, 'Fundamentals of Psychology', 'Physics');
 INSERT INTO [Course] values (388, 'Intro to Chemistry', 'Psychology');
 INSERT INTO [Course] values (389, 'Applied Engineering', 'History');
 INSERT INTO [Course] values (390, 'Advanced Chemistry', 'Sociology');
 INSERT INTO [Course] values (391, 'Principles of Biology', 'Biology');
 INSERT INTO [Course] values (392, 'Applied Mathematics', 'Mathematics');
 INSERT INTO [Course] values (393, 'Essentials of Chemistry', 'Biology');
 INSERT INTO [Course] values (394, 'Principles of Computer Science', 'Computer Science');
 INSERT INTO [Course] values (395, 'Principles of Biology', 'History');
 INSERT INTO [Course] values (396, 'Essentials of Computer Science', 'Mathematics');
 INSERT INTO [Course] values (397, 'Essentials of Physics', 'English');
 INSERT INTO [Course] values (398, 'Principles of Physics', 'Chemistry');
 INSERT INTO [Course] values (399, 'Essentials of History', 'Sociology');
 INSERT INTO [Course] values (400, 'Intro to Computer Science', 'Computer Science');
 INSERT INTO [Course] values (401, 'Fundamentals of Physics', 'Mathematics');
 INSERT INTO [Course] values (402, 'Intro to Physics', 'Physics');
 INSERT INTO [Course] values (403, 'Applied Chemistry', 'English');
 INSERT INTO [Course] values (404, 'Applied Sociology', 'History');
 INSERT INTO [Course] values (405, 'Essentials of Mathematics', 'Engineering');
 INSERT INTO [Course] values (406, 'Principles of Chemistry', 'English');
 INSERT INTO [Course] values (407, 'Intro to History', 'Mathematics');
 INSERT INTO [Course] values (408, 'Fundamentals of Computer Science', 'Psychology');
 INSERT INTO [Course] values (409, 'Fundamentals of Biology', 'English');
 INSERT INTO [Course] values (410, 'Fundamentals of History', 'Mathematics');
 INSERT INTO [Course] values (411, 'Principles of History', 'History');
 INSERT INTO [Course] values (412, 'Principles of Sociology', 'History');
 INSERT INTO [Course] values (413, 'Principles of Psychology', 'Computer Science');
 INSERT INTO [Course] values (414, 'Advanced Mathematics', 'Computer Science');
 INSERT INTO [Course] values (415, 'Principles of Psychology', 'English');
 INSERT INTO [Course] values (416, 'Essentials of Engineering', 'English');
 INSERT INTO [Course] values (417, 'Principles of Computer Science', 'Computer Science');
 INSERT INTO [Course] values (418, 'Principles of Mathematics', 'Mathematics');
 INSERT INTO [Course] values (419, 'Advanced Psychology', 'Physics');
 INSERT INTO [Course] values (420, 'Intro to Engineering', 'Computer Science');
 INSERT INTO [Course] values (421, 'Advanced Mathematics', 'Sociology');
 INSERT INTO [Course] values (422, 'Essentials of Engineering', 'Biology');
 INSERT INTO [Course] values (423, 'Advanced Computer Science', 'English');
 INSERT INTO [Course] values (424, 'Applied History', 'Engineering');
 INSERT INTO [Course] values (425, 'Principles of Mathematics', 'Biology');
 INSERT INTO [Course] values (426, 'Fundamentals of Chemistry', 'Computer Science');
 INSERT INTO [Course] values (427, 'Fundamentals of Psychology', 'Psychology');
 INSERT INTO [Course] values (428, 'Intro to Psychology', 'Physics');
 INSERT INTO [Course] values (429, 'Principles of Physics', 'Chemistry');
 INSERT INTO [Course] values (430, 'Advanced Psychology', 'Sociology');
 INSERT INTO [Course] values (431, 'Intro to Computer Science', 'Sociology');
 INSERT INTO [Course] values (432, 'Advanced Computer Science', 'English');
 INSERT INTO [Course] values (433, 'Principles of Sociology', 'Sociology');
 INSERT INTO [Course] values (434, 'Essentials of Psychology', 'Mathematics');
 INSERT INTO [Course] values (435, 'Intro to Psychology', 'Chemistry');
 INSERT INTO [Course] values (436, 'Intro to Physics', 'Computer Science');
 INSERT INTO [Course] values (437, 'Advanced History', 'English');
 INSERT INTO [Course] values (438, 'Intro to Biology', 'History');
 INSERT INTO [Course] values (439, 'Essentials of English', 'English');
 INSERT INTO [Course] values (440, 'Advanced Chemistry', 'Engineering');
 INSERT INTO [Course] values (441, 'Advanced History', 'Biology');
 INSERT INTO [Course] values (442, 'Intro to Mathematics', 'Computer Science');
 INSERT INTO [Course] values (443, 'Fundamentals of Sociology', 'English');
 INSERT INTO [Course] values (444, 'Intro to Mathematics', 'History');
 INSERT INTO [Course] values (445, 'Fundamentals of Engineering', 'Computer Science');
 INSERT INTO [Course] values (446, 'Fundamentals of Engineering', 'History');
 INSERT INTO [Course] values (447, 'Principles of Sociology', 'Sociology');
 INSERT INTO [Course] values (448, 'Intro to History', 'Psychology');
 INSERT INTO [Course] values (449, 'Essentials of History', 'Physics');
 INSERT INTO [Course] values (450, 'Intro to Chemistry', 'Physics');
 INSERT INTO [Course] values (451, 'Advanced Computer Science', 'History');
 INSERT INTO [Course] values (452, 'Principles of Biology', 'Chemistry');
 INSERT INTO [Course] values (453, 'Principles of History', 'Psychology');
 INSERT INTO [Course] values (454, 'Principles of Chemistry', 'Psychology');
 INSERT INTO [Course] values (455, 'Fundamentals of Engineering', 'Psychology');
 INSERT INTO [Course] values (456, 'Essentials of Physics', 'Chemistry');
 INSERT INTO [Course] values (457, 'Applied Biology', 'English');
 INSERT INTO [Course] values (458, 'Applied Chemistry', 'Physics');
 INSERT INTO [Course] values (459, 'Applied Mathematics', 'Chemistry');
 INSERT INTO [Course] values (460, 'Fundamentals of Chemistry', 'Biology');
 INSERT INTO [Course] values (461, 'Applied Sociology', 'Biology');
 INSERT INTO [Course] values (462, 'Fundamentals of Biology', 'Chemistry');
 INSERT INTO [Course] values (463, 'Fundamentals of Computer Science', 'Mathematics');
 INSERT INTO [Course] values (464, 'Fundamentals of Biology', 'Physics');
 INSERT INTO [Course] values (465, 'Intro to Computer Science', 'Mathematics');
 INSERT INTO [Course] values (466, 'Applied Engineering', 'Engineering');
 INSERT INTO [Course] values (467, 'Applied Chemistry', 'Computer Science');
 INSERT INTO [Course] values (468, 'Essentials of Mathematics', 'Chemistry');
 INSERT INTO [Course] values (469, 'Essentials of Sociology', 'Computer Science');
 INSERT INTO [Course] values (470, 'Advanced Biology', 'Physics');
 INSERT INTO [Course] values (471, 'Principles of Computer Science', 'Engineering');
 INSERT INTO [Course] values (472, 'Essentials of Engineering', 'Physics');
 INSERT INTO [Course] values (473, 'Advanced Physics', 'Engineering');
 INSERT INTO [Course] values (474, 'Intro to Engineering', 'Engineering');
 INSERT INTO [Course] values (475, 'Principles of Biology', 'Biology');
 INSERT INTO [Course] values (476, 'Advanced Chemistry', 'Mathematics');
 INSERT INTO [Course] values (477, 'Advanced Mathematics', 'History');
 INSERT INTO [Course] values (478, 'Essentials of Mathematics', 'Mathematics');
 INSERT INTO [Course] values (479, 'Intro to Physics', 'Engineering');
 INSERT INTO [Course] values (480, 'Principles of Mathematics', 'Physics');
 INSERT INTO [Course] values (481, 'Essentials of History', 'History');
 INSERT INTO [Course] values (482, 'Fundamentals of Computer Science', 'Biology');
 INSERT INTO [Course] values (483, 'Essentials of Biology', 'English');
 INSERT INTO [Course] values (484, 'Applied English', 'English');
 INSERT INTO [Course] values (485, 'Intro to Computer Science', 'Computer Science');
 INSERT INTO [Course] values (486, 'Essentials of English', 'Sociology');
 INSERT INTO [Course] values (487, 'Applied Chemistry', 'Psychology');
 INSERT INTO [Course] values (488, 'Principles of Mathematics', 'Mathematics');
 INSERT INTO [Course] values (489, 'Principles of Engineering', 'Psychology');
 INSERT INTO [Course] values (490, 'Applied Physics', 'Computer Science');
 INSERT INTO [Course] values (491, 'Fundamentals of Computer Science', 'Engineering');
 INSERT INTO [Course] values (492, 'Principles of English', 'Chemistry');
 INSERT INTO [Course] values (493, 'Advanced Biology', 'Engineering');
 INSERT INTO [Course] values (494, 'Principles of Computer Science', 'Biology');
 INSERT INTO [Course] values (495, 'Intro to Engineering', 'English');
 INSERT INTO [Course] values (496, 'Applied Computer Science', 'History');
 INSERT INTO [Course] values (497, 'Advanced History', 'Psychology');
 INSERT INTO [Course] values (498, 'Fundamentals of Engineering', 'Engineering');
 INSERT INTO [Course] values (499, 'Advanced Mathematics', 'Psychology');
 INSERT INTO [Course] values (500, 'Fundamentals of Mathematics', 'Engineering');
 